### ISSUE TITLE
Build is failing with polyfill installed

### ISSUE THREAD

**Issue by netes** [ember-polyfills/ember-cached-decorator-polyfill#41]
Hey!
I wanted to try the polyfill after installing and running Ember server I'm getting an error like below:
```
- broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/tmp/broccoli-2273133o861FNc2Y6/out-1148-broccoli_debug_debug_2_vendor_js/vendor/ember-cache-primitive-polyfill.js'
```

Polyfill is installed inside an engine, as a dependency (not `devDependency`). Do you have any idea what might be wrong? I tried installing `ember-cache-primitive-polyfill` manually but it didn't help.

**Comment by rwjblue** [comment]
I think this should be working properly now with 0.1.2
